name: Auto IPTV Update

on:
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা পর চলবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run Python Script
        run: python update_iptv.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add links.json
          git commit -m "Auto Update Channels" || echo "No changes to commit"
          git push origin main
